services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soccer_ai_api
    restart: always
    ports:
      - "10000:8080"
    environment:
      - PORT=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=/app/data/soccer.db
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
