// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoccerAi.Infrastructure.Persistence;

#nullable disable

namespace SoccerAi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260714140000_AddSyncState")]
    partial class AddSyncState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SoccerAi.Application.Entities.BacktestReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Stake")
                        .HasColumnType("REAL");

                    b.Property<int>("WeeksBack")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeeksBack", "Stake", "CreatedAt");

                    b.ToTable("BacktestReports", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.Combination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDailyCache")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalOdds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Language", "IsDailyCache");

                    b.ToTable("Combinations", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayBallPossession")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AwayElo")
                        .HasColumnType("REAL");

                    b.Property<int>("AwayGoal")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AwayGoalAvg")
                        .HasColumnType("REAL");

                    b.Property<int?>("AwayPassesAccurate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayRedCards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayShots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayShotsOnTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AwayWinOdds")
                        .HasColumnType("REAL");

                    b.Property<double>("AwayXg")
                        .HasColumnType("REAL");

                    b.Property<double?>("BttsYesOdds")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DrawOdds")
                        .HasColumnType("REAL");

                    b.Property<int?>("HomeBallPossession")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HomeElo")
                        .HasColumnType("REAL");

                    b.Property<int>("HomeGoal")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HomeGoalAvg")
                        .HasColumnType("REAL");

                    b.Property<int?>("HomePassesAccurate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeRedCards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeShots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeShotsOnTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HomeWinOdds")
                        .HasColumnType("REAL");

                    b.Property<double>("HomeXg")
                        .HasColumnType("REAL");

                    b.Property<int>("HtAwayGoal")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HtAwayGoalAvg")
                        .HasColumnType("REAL");

                    b.Property<int>("HtHomeGoal")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HtHomeGoalAvg")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsCurrentSeason")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDerby")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Over25Odds")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Under25Odds")
                        .HasColumnType("REAL");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApiId")
                        .IsUnique();

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Fixtures", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.FixtureAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiAwayWinQualified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiBestBet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AiBttsQualified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiGoals23Qualified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiHomeWinQualified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiOver25Qualified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AiOverallConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiUnder25Qualified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Analysis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("AwayProb")
                        .HasColumnType("REAL");

                    b.Property<string>("AwayWinSummary")
                        .HasColumnType("TEXT");

                    b.Property<double>("BttsProb")
                        .HasColumnType("REAL");

                    b.Property<string>("BttsSummary")
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ConsensusEvaluation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DrawProb")
                        .HasColumnType("REAL");

                    b.Property<int>("FixtureId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HomeProb")
                        .HasColumnType("REAL");

                    b.Property<string>("HomeWinSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<double>("Over25Prob")
                        .HasColumnType("REAL");

                    b.Property<string>("Over25Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("PredictionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrapDetected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrapReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Under25Summary")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId", "Lang")
                        .IsUnique();

                    b.ToTable("FixtureAnalyses", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCompletedStep")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastRunStartedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSuccessfulSyncUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncStates", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Draw")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Elo")
                        .HasColumnType("REAL");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsDiff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lose")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ManagerAppointedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Played")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Win")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApiId")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.Fixture", b =>
                {
                    b.HasOne("SoccerAi.Application.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .HasPrincipalKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoccerAi.Application.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .HasPrincipalKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.FixtureAnalysis", b =>
                {
                    b.HasOne("SoccerAi.Application.Entities.Fixture", null)
                        .WithMany("Analyses")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.Fixture", b =>
                {
                    b.Navigation("Analyses");
                });
#pragma warning restore 612, 618
        }
    }
}
