// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoccerAi.Infrastructure.Persistence;

#nullable disable

namespace SoccerAi.Infrastructure.Persistence.Migrations.Postgres
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20260911135115_RecordAiProvenancePostgres")]
    partial class RecordAiProvenancePostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoccerAi.Application.Entities.BacktestReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Stake")
                        .HasColumnType("double precision");

                    b.Property<int>("WeeksBack")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeeksBack", "Stake", "CreatedAt");

                    b.ToTable("BacktestReports", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.Combination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDailyCache")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalOdds")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Language", "IsDailyCache");

                    b.ToTable("Combinations", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiId")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayBallPossession")
                        .HasColumnType("integer");

                    b.Property<double?>("AwayElo")
                        .HasColumnType("double precision");

                    b.Property<int>("AwayGoal")
                        .HasColumnType("integer");

                    b.Property<double>("AwayGoalAvg")
                        .HasColumnType("double precision");

                    b.Property<double?>("AwayObservedXg")
                        .HasColumnType("double precision");

                    b.Property<int?>("AwayPassesAccurate")
                        .HasColumnType("integer");

                    b.Property<int>("AwayRedCards")
                        .HasColumnType("integer");

                    b.Property<int>("AwayShots")
                        .HasColumnType("integer");

                    b.Property<int>("AwayShotsOnTarget")
                        .HasColumnType("integer");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<double?>("AwayWinOdds")
                        .HasColumnType("double precision");

                    b.Property<double>("AwayXg")
                        .HasColumnType("double precision");

                    b.Property<double?>("BttsYesOdds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DrawOdds")
                        .HasColumnType("double precision");

                    b.Property<int?>("HomeBallPossession")
                        .HasColumnType("integer");

                    b.Property<double?>("HomeElo")
                        .HasColumnType("double precision");

                    b.Property<int>("HomeGoal")
                        .HasColumnType("integer");

                    b.Property<double>("HomeGoalAvg")
                        .HasColumnType("double precision");

                    b.Property<double?>("HomeObservedXg")
                        .HasColumnType("double precision");

                    b.Property<int?>("HomePassesAccurate")
                        .HasColumnType("integer");

                    b.Property<int>("HomeRedCards")
                        .HasColumnType("integer");

                    b.Property<int>("HomeShots")
                        .HasColumnType("integer");

                    b.Property<int>("HomeShotsOnTarget")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<double?>("HomeWinOdds")
                        .HasColumnType("double precision");

                    b.Property<double>("HomeXg")
                        .HasColumnType("double precision");

                    b.Property<int>("HtAwayGoal")
                        .HasColumnType("integer");

                    b.Property<double>("HtAwayGoalAvg")
                        .HasColumnType("double precision");

                    b.Property<int>("HtHomeGoal")
                        .HasColumnType("integer");

                    b.Property<double>("HtHomeGoalAvg")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("InjuriesCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurrentSeason")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDerby")
                        .HasColumnType("boolean");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("OddsCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("OddsUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Over25Odds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("StatisticsUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double?>("Under25Odds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApiId")
                        .IsUnique();

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Fixtures", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.FixtureAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AiAwayWinQualified")
                        .HasColumnType("boolean");

                    b.Property<string>("AiBestBet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AiBttsQualified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("AiGeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AiGoals23Qualified")
                        .HasColumnType("boolean");

                    b.Property<bool>("AiHomeWinQualified")
                        .HasColumnType("boolean");

                    b.Property<string>("AiInputHash")
                        .HasColumnType("text");

                    b.Property<string>("AiModelVersion")
                        .HasColumnType("text");

                    b.Property<bool>("AiOver25Qualified")
                        .HasColumnType("boolean");

                    b.Property<int>("AiOverallConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("AiPromptHash")
                        .HasColumnType("text");

                    b.Property<bool>("AiUnder25Qualified")
                        .HasColumnType("boolean");

                    b.Property<string>("Analysis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AwayProb")
                        .HasColumnType("double precision");

                    b.Property<string>("AwayWinSummary")
                        .HasColumnType("text");

                    b.Property<double>("BttsProb")
                        .HasColumnType("double precision");

                    b.Property<string>("BttsSummary")
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("ConsensusEvaluation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DrawProb")
                        .HasColumnType("double precision");

                    b.Property<int>("FixtureId")
                        .HasColumnType("integer");

                    b.Property<double>("Goals23Prob")
                        .HasColumnType("double precision");

                    b.Property<double>("HomeProb")
                        .HasColumnType("double precision");

                    b.Property<string>("HomeWinSummary")
                        .HasColumnType("text");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<double>("Over25Prob")
                        .HasColumnType("double precision");

                    b.Property<string>("Over25Summary")
                        .HasColumnType("text");

                    b.Property<string>("PredictionReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("text");

                    b.Property<bool>("TrapDetected")
                        .HasColumnType("boolean");

                    b.Property<string>("TrapReason")
                        .HasColumnType("text");

                    b.Property<string>("Under25Summary")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId", "Lang")
                        .IsUnique();

                    b.ToTable("FixtureAnalyses", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.FixtureInjury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FixtureId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("KickoffUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerApiId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TeamApiId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("FixtureId", "PlayerApiId", "CapturedAtUtc")
                        .IsUnique();

                    b.ToTable("FixtureInjuries", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.FixtureOddsQuote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bookmaker")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FixtureId")
                        .HasColumnType("integer");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("ProviderUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId", "Market");

                    b.ToTable("FixtureOddsQuotes", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.ModelForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualAwayGoals")
                        .HasColumnType("integer");

                    b.Property<int?>("ActualHomeGoals")
                        .HasColumnType("integer");

                    b.Property<double>("BttsProbability")
                        .HasColumnType("double precision");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<double>("ExpectedGoals")
                        .HasColumnType("double precision");

                    b.Property<int>("FixtureId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("KickoffUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<double>("Over25Probability")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("PredictedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PredictedAwayGoals")
                        .HasColumnType("integer");

                    b.Property<int>("PredictedHomeGoals")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("SettledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("SystemBttsProbability")
                        .HasColumnType("double precision");

                    b.Property<double>("SystemExpectedGoals")
                        .HasColumnType("double precision");

                    b.Property<double>("SystemOver25Probability")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId", "Model")
                        .IsUnique();

                    b.HasIndex("Model", "SettledAtUtc");

                    b.HasIndex("SettledAtUtc", "KickoffUtc");

                    b.ToTable("ModelForecasts", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.PredictionSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Away")
                        .HasColumnType("double precision");

                    b.Property<double>("Btts")
                        .HasColumnType("double precision");

                    b.Property<bool>("BttsPick")
                        .HasColumnType("boolean");

                    b.Property<long>("CaptureWindow")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Draw")
                        .HasColumnType("double precision");

                    b.Property<int>("FixtureId")
                        .HasColumnType("integer");

                    b.Property<double>("Goals23")
                        .HasColumnType("double precision");

                    b.Property<bool>("Goals23Pick")
                        .HasColumnType("boolean");

                    b.Property<double>("Home")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("KickoffUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Over25")
                        .HasColumnType("double precision");

                    b.Property<bool>("Over25Pick")
                        .HasColumnType("boolean");

                    b.Property<double>("RawAway")
                        .HasColumnType("double precision");

                    b.Property<double>("RawBtts")
                        .HasColumnType("double precision");

                    b.Property<double>("RawDraw")
                        .HasColumnType("double precision");

                    b.Property<double>("RawGoals23")
                        .HasColumnType("double precision");

                    b.Property<double>("RawHome")
                        .HasColumnType("double precision");

                    b.Property<double>("RawOver25")
                        .HasColumnType("double precision");

                    b.Property<string>("Winner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KickoffUtc");

                    b.HasIndex("FixtureId", "CaptureWindow")
                        .IsUnique();

                    b.ToTable("PredictionSnapshots", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.PublishedTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("BoardDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CombinedProbability")
                        .HasColumnType("double precision");

                    b.Property<double>("Ev")
                        .HasColumnType("double precision");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("KellyStake")
                        .HasColumnType("double precision");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SettledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double>("TotalOdds")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("BoardDateUtc", "Status");

                    b.ToTable("PublishedTickets", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.PublishedTicketLeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Ev")
                        .HasColumnType("double precision");

                    b.Property<int>("FixtureId")
                        .HasColumnType("integer");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("Odds")
                        .HasColumnType("double precision");

                    b.Property<double>("Probability")
                        .HasColumnType("double precision");

                    b.Property<int>("PublishedTicketId")
                        .HasColumnType("integer");

                    b.Property<string>("Selection")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("PublishedTicketId");

                    b.ToTable("PublishedTicketLegs", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LastCompletedStep")
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastRunStartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SyncStates", (string)null);
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiId")
                        .HasColumnType("integer");

                    b.Property<int>("Draw")
                        .HasColumnType("integer");

                    b.Property<double>("Elo")
                        .HasColumnType("double precision");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsDiff")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("Lose")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ManagerAppointedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagerName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Played")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Win")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiId")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.Fixture", b =>
                {
                    b.HasOne("SoccerAi.Application.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .HasPrincipalKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoccerAi.Application.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .HasPrincipalKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.FixtureAnalysis", b =>
                {
                    b.HasOne("SoccerAi.Application.Entities.Fixture", null)
                        .WithMany("Analyses")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.FixtureOddsQuote", b =>
                {
                    b.HasOne("SoccerAi.Application.Entities.Fixture", null)
                        .WithMany()
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.PublishedTicketLeg", b =>
                {
                    b.HasOne("SoccerAi.Application.Entities.PublishedTicket", null)
                        .WithMany("Legs")
                        .HasForeignKey("PublishedTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.Fixture", b =>
                {
                    b.Navigation("Analyses");
                });

            modelBuilder.Entity("SoccerAi.Application.Entities.PublishedTicket", b =>
                {
                    b.Navigation("Legs");
                });
#pragma warning restore 612, 618
        }
    }
}
