namespace SoccerAi.Application.Entities;

/// <summary>
/// Persists the complex JSON list generated by Gemini's Combination builder.
/// Caches combinations by Date and Language to prevent duplicate API generation 
/// overhead on the same pool of matches.
/// </summary>
public class DailyCombination
{
    public int Id { get; set; }
    
    /// <summary>
    /// The target date boundary (00:00:00 UTC) stored internally as EF Ticks
    /// </summary>
    public DateTimeOffset Date { get; set; }
    
    public string Language { get; set; } = "en";
    
    /// <summary>
    /// Serialized JSON array of CombinationDto
    /// </summary>
    public string Payload { get; set; } = string.Empty;

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
}
