using FluentAssertions;
using SoccerAi.Application.Services;
using SoccerAi.Application.Services.Forecasts;

namespace soccer_ai_unit_tests.Services;

public class MarketLambdaSolverTests
{
    /// <summary>
    /// Builds the fair 1X2 and Over/Under prices a given λ pair implies, then
    /// adds a bookmaker margin. Round-tripping through these is how the solver
    /// is checked: feed it prices generated by a known λ and see whether it
    /// recovers that λ.
    /// </summary>
    private static (double Home, double Draw, double Away, double Over, double Under) PricesFor(
        double lambdaHome, double lambdaAway, double margin = 1.06)
    {
        var m = DixonColesMath.ComputeMarkets(
            DixonColesMath.BuildScoreMatrix(
                lambdaHome, lambdaAway,
                MarketLambdaSolver.DefaultRho, MarketLambdaSolver.DefaultMaxGoals));

        return (margin / m.HomeWin, margin / m.Draw, margin / m.AwayWin,
                margin / m.Over25, margin / (1 - m.Over25));
    }

    [Theory]
    [InlineData(1.5, 1.1)]
    [InlineData(2.1, 0.8)]
    [InlineData(1.0, 1.0)]
    [InlineData(0.9, 1.6)]
    public void Solve_RecoversTheLambdaPairThatGeneratedThePrices(double lh, double la)
    {
        var (home, draw, away, over, under) = PricesFor(lh, la);

        var solved = MarketLambdaSolver.Solve(home, draw, away, over, under);

        solved.Should().NotBeNull();
        // The grid step is 0.05, so half a step is the best achievable accuracy.
        solved!.Value.LambdaHome.Should().BeApproximately(lh, 0.06);
        solved.Value.LambdaAway.Should().BeApproximately(la, 0.06);
    }

    [Fact]
    public void Solve_ImpliedBttsMatchesTheMatrixForTheRecoveredPair()
    {
        var (home, draw, away, over, under) = PricesFor(1.6, 1.2);
        var solved = MarketLambdaSolver.Solve(home, draw, away, over, under)!.Value;

        var expected = DixonColesMath.ComputeMarkets(
            DixonColesMath.BuildScoreMatrix(
                solved.LambdaHome, solved.LambdaAway,
                MarketLambdaSolver.DefaultRho, MarketLambdaSolver.DefaultMaxGoals)).Btts;

        solved.Btts.Should().BeApproximately(expected, 1e-9);
    }

    [Fact]
    public void Solve_WorksFromOverUnderAlone()
    {
        // The whole point of the solver: BTTS odds are missing on ~93% of
        // fixtures, so it has to produce something useful from the prices that
        // do exist.
        var (_, _, _, over, under) = PricesFor(1.5, 1.3);

        var solved = MarketLambdaSolver.Solve(null, null, null, over, under);

        solved.Should().NotBeNull();
        // Over/Under fixes the TOTAL but says nothing about the split, so only
        // the sum is recoverable from it.
        (solved!.Value.LambdaHome + solved.Value.LambdaAway)
            .Should().BeApproximately(2.8, 0.25);
    }

    [Fact]
    public void Solve_WorksFrom1X2Alone()
    {
        var (home, draw, away, _, _) = PricesFor(1.7, 1.0);

        var solved = MarketLambdaSolver.Solve(home, draw, away, null, null);

        solved.Should().NotBeNull();
        solved!.Value.LambdaHome.Should().BeGreaterThan(solved.Value.LambdaAway);
    }

    [Fact]
    public void Solve_ReturnsNullWithNoUsablePrices()
    {
        MarketLambdaSolver.Solve(null, null, null, null, null).Should().BeNull();
    }

    [Fact]
    public void Solve_ReturnsNullWhenOddsAreCorrupt()
    {
        // 185 instead of 1.85 is a real shape of bad data in this feed; it must
        // not be silently inverted into a probability of 0.005.
        MarketLambdaSolver.Solve(185, 320, 410, null, null).Should().BeNull();
    }

    [Fact]
    public void Solve_HigherOverPriceImpliesFewerGoals()
    {
        // A longer price on Over 2.5 means the market expects fewer goals.
        var low = MarketLambdaSolver.Solve(null, null, null, 1.60, 2.40)!.Value;
        var high = MarketLambdaSolver.Solve(null, null, null, 2.40, 1.60)!.Value;

        (high.LambdaHome + high.LambdaAway)
            .Should().BeLessThan(low.LambdaHome + low.LambdaAway);
    }

    [Fact]
    public void Solve_ImpliedProbabilitiesAreInRange()
    {
        var (home, draw, away, over, under) = PricesFor(2.4, 1.9);
        var solved = MarketLambdaSolver.Solve(home, draw, away, over, under)!.Value;

        solved.Btts.Should().BeInRange(0, 1);
        solved.Over25.Should().BeInRange(0, 1);
        solved.Residual.Should().BeGreaterThanOrEqualTo(0);
    }

    [Fact]
    public void Solve_MutuallyInconsistentPricesReportALargeResidual()
    {
        // 1X2 saying "crushing home favourite" while Over/Under says "very low
        // scoring" cannot both come from one λ pair. The residual is what lets a
        // caller notice that rather than trusting the closest bad fit.
        var consistent = MarketLambdaSolver.Solve(1.30, 5.50, 9.00, 1.55, 2.45)!.Value;
        var contradictory = MarketLambdaSolver.Solve(1.30, 5.50, 9.00, 4.50, 1.20)!.Value;

        contradictory.Residual.Should().BeGreaterThan(consistent.Residual);
    }
}
