<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RollForward>LatestMajor</RollForward>
    <RootNamespace>soccer_gpt_api</RootNamespace>
    <UserSecretsId>714295b9-82ec-4a8b-ae72-6c59a8c87cf2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Net" Version="4.9.0" />
    <PackageReference Include="Mediator.Net.MicrosoftDependencyInjection" Version="4.9.0" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.11.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\soccer-gpt-application\soccer-gpt-application.csproj" />
    <ProjectReference Include="..\soccer-gpt-infrastructure\soccer-gpt-infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Data\european_fixtures\european_teams_lookup.json" />
    <_ContentIncludedByDefault Remove="Data\european_fixtures\ucl_fixtures.json" />
    <_ContentIncludedByDefault Remove="Data\european_fixtures\uel_fixtures.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
