<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>soccer_gpt_api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\soccer-gpt-application\soccer-gpt-application.csproj" />
    <ProjectReference Include="..\soccer-gpt-infrastructure\soccer-gpt-infrastructure.csproj" />
  </ItemGroup>

</Project>
