// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using soccer_gpt_infrastructure.Persistence;

#nullable disable

namespace soccer_gpt_infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225192220_EnforceFixtureTeamConstraints")]
    partial class EnforceFixtureTeamConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("soccer_gpt_application.Entities.Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayBallPossession")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayGoal")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AwayGoalAvg")
                        .HasColumnType("REAL");

                    b.Property<int?>("AwayPassesAccurate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayShots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayShotsOnTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AwayWinOdds")
                        .HasColumnType("REAL");

                    b.Property<double>("AwayXg")
                        .HasColumnType("REAL");

                    b.Property<double?>("BttsYesOdds")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DrawOdds")
                        .HasColumnType("REAL");

                    b.Property<string>("GeminiAnalysis")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeminiAwayWinSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeminiBttsSummary")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GeminiConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("GeminiHomeWinSummary")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("GeminiIsTrap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeminiOneLineSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeminiOver25Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeminiReasoning")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeminiRecommendation")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeminiTrapReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeminiUnder25Summary")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HomeBallPossession")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeGoal")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HomeGoalAvg")
                        .HasColumnType("REAL");

                    b.Property<int?>("HomePassesAccurate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeShots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeShotsOnTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HomeWinOdds")
                        .HasColumnType("REAL");

                    b.Property<double>("HomeXg")
                        .HasColumnType("REAL");

                    b.Property<int>("HtAwayGoal")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HtAwayGoalAvg")
                        .HasColumnType("REAL");

                    b.Property<int>("HtHomeGoal")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HtHomeGoalAvg")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsCurrentSeason")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDerby")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Over25Odds")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Under25Odds")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiId")
                        .IsUnique();

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Fixtures", t =>
                        {
                            t.HasCheckConstraint("CK_Fixtures_HomeAwayDifferent", "\"HomeTeamId\" <> \"AwayTeamId\"");
                        });
                });

            modelBuilder.Entity("soccer_gpt_application.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Draw")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsDiff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lose")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Played")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Win")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApiId")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("soccer_gpt_application.Entities.UserCombination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalOdds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("UserCombinations");
                });

            modelBuilder.Entity("soccer_gpt_application.Entities.UserCombinationMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int>("FixtureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Odds")
                        .HasColumnType("REAL");

                    b.Property<string>("Prediction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserCombinationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserCombinationId");

                    b.ToTable("UserCombinationMatches");
                });

            modelBuilder.Entity("soccer_gpt_application.Entities.Fixture", b =>
                {
                    b.HasOne("soccer_gpt_application.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .HasPrincipalKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("soccer_gpt_application.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .HasPrincipalKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("soccer_gpt_application.Entities.UserCombinationMatch", b =>
                {
                    b.HasOne("soccer_gpt_application.Entities.UserCombination", "UserCombination")
                        .WithMany("Matches")
                        .HasForeignKey("UserCombinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCombination");
                });

            modelBuilder.Entity("soccer_gpt_application.Entities.UserCombination", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
