using System.Data;
using System.Globalization;
using System.Text;
using ExcelDataReader;
using Mediator.Net.Context;
using Mediator.Net.Contracts;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using soccer_gpt_application.Entities;
using soccer_gpt_application.Interfaces;

namespace soccer_gpt_application.Features.DataManagement.Commands;

public class UploadUpcomingFixturesCommandHandler(
    IApplicationDbContext dbContext,
    ILeagueService leagueService,
    ITeamNameNormalizer teamNameNormalizer,
    ILogger<UploadUpcomingFixturesCommandHandler> logger)
    : ICommandHandler<UploadUpcomingFixturesCommand, UploadUpcomingFixturesResponse>
{
    public async Task<UploadUpcomingFixturesResponse> Handle(IReceiveContext<UploadUpcomingFixturesCommand> context, CancellationToken cancellationToken)
    {
        var cmd = context.Message;
        
        // Response Counters
        int processed = 0;
        int valid = 0;
        int added = 0;
        int skippedDuplicate = 0;
        int skippedInvalid = 0;
        var errors = new List<string>();

        // 1. Load Existing Signatures (In-Memory Check)
        var existingSignatures = await dbContext.Fixtures
            .AsNoTracking()
            .Select(f => new { f.Date, f.Time, f.LeagueName, f.HomeName, f.AwayName })
            .ToListAsync(cancellationToken);

        var signatureSet = new HashSet<string>(existingSignatures.Select(
            f => CreateSignature(f.Date, f.Time, f.LeagueName, f.HomeName, f.AwayName)));

        // 2. Prepare Reader
        using var reader = ExcelReaderFactory.CreateCsvReader(cmd.FileStream, new ExcelReaderConfiguration
        {
            FallbackEncoding = Encoding.GetEncoding(1252)
        });

        var dataSet = reader.AsDataSet(new ExcelDataSetConfiguration
        {
            ConfigureDataTable = _ => new ExcelDataTableConfiguration { UseHeaderRow = true }
        });

        if (dataSet.Tables.Count == 0) return new UploadUpcomingFixturesResponse { Errors = ["Empty CSV"] };

        var table = dataSet.Tables[0];
        
        // 3. Transaction
        using var transaction = await dbContext.Database.BeginTransactionAsync(cancellationToken);

        try
        {
            var fixturesToAdd = new List<Fixture>();
            
            foreach (DataRow row in table.Rows)
            {
                if (cancellationToken.IsCancellationRequested) break;
                processed++;

                // Column Mapping (Safe Access)
                string? GetCol(string name) => table.Columns.Contains(name) ? row[name]?.ToString()?.Trim() : null;

                var div = GetCol("Div");
                var dateStr = GetCol("Date");
                var timeStr = GetCol("Time");
                var homeRaw = GetCol("HomeTeam");
                var awayRaw = GetCol("AwayTeam");
                
                // 4. Strict Validation
                if (string.IsNullOrEmpty(div) || string.IsNullOrEmpty(dateStr) || 
                    string.IsNullOrEmpty(homeRaw) || string.IsNullOrEmpty(awayRaw))
                {
                    skippedInvalid++;
                    continue; // Log summary later if needed, prompt says summary errors
                }

                // Normalization
                var leagueName = leagueService.GetLeagueNameFromCode(div);
                var homeName = teamNameNormalizer.Normalize(homeRaw);
                var awayName = teamNameNormalizer.Normalize(awayRaw);

                if (homeName.Equals(awayName, StringComparison.OrdinalIgnoreCase))
                {
                    skippedInvalid++;
                    errors.Add($"Row {processed}: Home team same as Away ({homeName})");
                    continue;
                }

                // Date Parsing
                if (!DateTime.TryParse(dateStr, CultureInfo.InvariantCulture, DateTimeStyles.None, out var date))
                {
                     // Try fallback formats if needed, usually Invariant is strictly YYYY-MM-DD for csvs generated by us
                     // But if user uploads Excel, it might be different. Let's stick to standard parse for now or robust one
                     if (!DateTime.TryParse(dateStr, out date))
                     {
                         skippedInvalid++;
                          continue;
                     }
                }
                
                // Time Parsing
                TimeSpan time = TimeSpan.Zero;
                if (!string.IsNullOrEmpty(timeStr))
                {
                    if (TimeSpan.TryParse(timeStr, out var t)) time = t;
                    else if (DateTime.TryParse(timeStr, out var dt)) time = dt.TimeOfDay;
                }

                // 2. Uniqueness Check (In-Memory)
                var signature = CreateSignature(date, time, leagueName, homeName, awayName);
                if (signatureSet.Contains(signature))
                {
                    skippedDuplicate++;
                    continue;
                }

                // 5. Odds Parsing (Nullable, CultureInvariant, Strict)
                double? ParseOdd(string col)
                {
                    var valStr = GetCol(col);
                    if (string.IsNullOrEmpty(valStr)) return null;
                    
                    if (double.TryParse(valStr, NumberStyles.Any, CultureInfo.InvariantCulture, out var result))
                    {
                        return result > 0 ? result : null;
                    }
                    return null;
                }

                var fixture = new Fixture
                {
                    Date = date,
                    Time = time,
                    LeagueName = leagueName,
                    HomeName = homeName,
                    AwayName = awayName,
                    HomeOdds = ParseOdd("HomeOdds") ?? ParseOdd("1") ?? ParseOdd("HomeWin"),
                    DrawOdds = ParseOdd("DrawOdds") ?? ParseOdd("X") ?? ParseOdd("Draw"),
                    AwayOdds = ParseOdd("AwayOdds") ?? ParseOdd("2") ?? ParseOdd("AwayWin"),
                    Over25Odds = ParseOdd("Over25Odds") ?? ParseOdd("O2.5"),
                    Under25Odds = ParseOdd("Under25Odds") ?? ParseOdd("U2.5"),
                    BttsOdds = ParseOdd("BttsOdds") ?? ParseOdd("BTTS_Yes"),
                    TwoToThreeGoalsOdds = ParseOdd("TwoToThreeGoalsOdds"),
                    Played = false
                };

                fixturesToAdd.Add(fixture);
                signatureSet.Add(signature); // Prevent dups within same file
                valid++;
            }

            if (fixturesToAdd.Count > 0)
            {
                dbContext.Fixtures.AddRange(fixturesToAdd);
                await dbContext.SaveChangesAsync(cancellationToken);
                added = fixturesToAdd.Count;
            }

            await transaction.CommitAsync(cancellationToken);
        }
        catch (Exception ex)
        {
            await transaction.RollbackAsync(cancellationToken);
            logger.LogError(ex, "Failed to upload fixtures. Rolling back.");
            return new UploadUpcomingFixturesResponse 
            { 
                Errors = ["Transaction failed: " + ex.Message] 
            };
        }

        return new UploadUpcomingFixturesResponse
        {
            ProcessedCount = processed,
            ValidCount = valid,
            AddedCount = added,
            SkippedDuplicate = skippedDuplicate,
            SkippedInvalid = skippedInvalid,
            Errors = errors.Take(10).ToList() // Return first 10 errors
        };
    }

    private static string CreateSignature(DateTime date, TimeSpan time, string league, string home, string away)
    {
        return $"{date:yyyyMMdd}_{time:hhmm}_{league}_{home}_{away}".ToUpperInvariant();
    }
}
